# Generated by Django 3.0.2 on 2021-06-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColdCoffee',
            new_name='NgoDonation',
        ),
    ]
